# Mapping Campaign

mapping_channel = {
    "AS": "Apple Search Ads",
    "AB": "Apple Search Ads Brand",
    "CA": "Client Area",
    "HS": "eMail offre",
    "EV": "Event",
    "FP": "Facebook / Instagram Paid",
    "FO": "Facebook / Instagram Organic",
    "BB": "Bing Brand",
    "BS": "Bing Search",
    "GA": "Google App Campaigns",
    "GB": "Google Brand",
    "GD": "Google Display",
    "GM": "Google Performance Max",
    "GS": "Google Search",
    "GG": "Google DemandGen",
    "IB": "Introducing Brokers",
    "LI": "Linkedin Ads",
    "LO": "Linkedin Organic",
    "NL": "Newsletter",
    "PS": "Partnership",
    "XD": "Programmatic",
    "DB": "Programmatic Direct Booking",
    "PR": "Public Relations",
    "TA": "Taboola",
    "TW": "Twitter",
    "TO": "Twitter Organic",
    "YH": "Yahoo DSP",
    "YT": "Youtube Ads",
    "": "Missing",
    "NA": "Missing",
}

mapping_market = {
    "CH": "Switzerland",
    "FR": "France",
    "PL": "Poland",
    "IT": "Italia",
    "TR": "Turkey",
    "DE": "Deutschland",
    "WW": "WorldWide",
    "": "Switzerland",
    "NA": "Switzerland",
    "AS": "Asia",
    "CN": "China",
    "JO": "Jordan",
    "EU": "Europe",
    "EG": "Egypt",
    "ME": "Middle-East",
    "CY": "Cyprus",
    "DK": "Denmark",
    "UK": "United Kingdom",
    "AE": "United Arab Emirates",
}

mapping_language = {
    "en": "English",
    "fr": "French",
    "pl": "Polish",
    "it": "Italian",
    "tr": "Turkish",
    "de": "German",
    "ml": "MultiLanguages",
    "": "English",
    "NA": "English",
}
